/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-01 14:59:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/output.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"bg-white border border-4 rounded-lg shadow relative m-10\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex items-start justify-between p-5 border-b rounded-t\">\r\n");
      out.write("        <h3 class=\"text-xl font-semibold\">\r\n");
      out.write("            Add new product\r\n");
      out.write("        </h3>\r\n");
      out.write("        <button type=\"button\" class=\"text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center\" data-modal-toggle=\"product-modal\">\r\n");
      out.write("           <svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z\" clip-rule=\"evenodd\"></path></svg>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"p-6 space-y-6\">\r\n");
      out.write("        <form action=\"#\">\r\n");
      out.write("            <div class=\"grid grid-cols-6 gap-6\">\r\n");
      out.write("                <div class=\"col-span-6 sm:col-span-3\">\r\n");
      out.write("                    <label for=\"product-name\" class=\"text-sm font-medium text-gray-900 block mb-2\">Product Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"product-name\" id=\"product-name\" class=\"shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5\" placeholder=\"Apple Imac 27”\" required=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-span-6 sm:col-span-3\">\r\n");
      out.write("                    <label for=\"category\" class=\"text-sm font-medium text-gray-900 block mb-2\">Category</label>\r\n");
      out.write("                    <select id=\"category\" name=\"category\" class=\"shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5\" required=\"\">\r\n");
      out.write("    <option value=\"\" disabled selected>Select category</option>\r\n");
      out.write("    <option value=\"Smartphones & Accessories\">Smartphones & Accessories</option>\r\n");
      out.write("    <option value=\"Computers & Laptops\">Computers & Laptops</option>\r\n");
      out.write("    <option value=\"Home Entertainment\">Home Entertainment</option>\r\n");
      out.write("    <option value=\"Photography & Cameras\">Photography & Cameras</option>\r\n");
      out.write("    <option value=\"Wearable Technology\">Wearable Technology</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-span-6 sm:col-span-3\">\r\n");
      out.write("                    <label for=\"brand\" class=\"text-sm font-medium text-gray-900 block mb-2\">Brand</label>\r\n");
      out.write("                    <input type=\"text\" name=\"brand\" id=\"brand\" class=\"shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5\" placeholder=\"Apple\" required=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-span-6 sm:col-span-3\">\r\n");
      out.write("                    <label for=\"price\" class=\"text-sm font-medium text-gray-900 block mb-2\">Price</label>\r\n");
      out.write("                    <input type=\"number\" name=\"price\" id=\"price\" class=\"shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5\" placeholder=\"2300\" required=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-span-6 sm:col-span-3\">\r\n");
      out.write("                    <label for=\"image-url\" class=\"text-sm font-medium text-gray-900 block mb-2\">Image URL</label>\r\n");
      out.write("                    <input type=\"text\" name=\"image-url\" id=\"image-url\" class=\"shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5\" placeholder=\"Image URL\" required=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-span-full\">\r\n");
      out.write("                    <label for=\"product-details\" class=\"text-sm font-medium text-gray-900 block mb-2\">Product Details</label>\r\n");
      out.write("                    <textarea id=\"product-details\" rows=\"6\" class=\"bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4\" placeholder=\"Details\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"p-6 border-t border-gray-200 rounded-b\">\r\n");
      out.write("        <button class=\"text-white bg-cyan-600 hover:bg-cyan-700 focus:ring-4 focus:ring-cyan-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center\" type=\"submit\">Save changes</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
