/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-02 05:48:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/html/navbar.jsp", Long.valueOf(1711982817614L));
    _jspx_dependants.put("/html/footer.jsp", Long.valueOf(1711981700381L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/output.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/output.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"max-h-[70px]\">\r\n");
      out.write("    <div class=\"flex justify-between mt-2\">\r\n");
      out.write("        <div class=\"ml-5 flex items-center\">\r\n");
      out.write("            <svg class=\"w-8 text-deep-purple-accent-400\" viewBox=\"0 0 24 24\" stroke-linejoin=\"round\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-miterlimit=\"10\" stroke=\"currentColor\" fill=\"none\">\r\n");
      out.write("                <rect x=\"3\" y=\"1\" width=\"7\" height=\"12\"></rect>\r\n");
      out.write("                <rect x=\"3\" y=\"17\" width=\"7\" height=\"6\"></rect>\r\n");
      out.write("                <rect x=\"14\" y=\"1\" width=\"7\" height=\"6\"></rect>\r\n");
      out.write("                <rect x=\"14\" y=\"11\" width=\"7\" height=\"12\"></rect>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("            <input type=\"text\" class=\"h-[40px] border border-b-gray-200 pl-4 rounded-s-full\" placeholder=\"Search\">\r\n");
      out.write("            <div class=\"h-[40px] border border-b-gray-200 rounded-e-full hover:bg-slate-200 hover:border-indigo-700 \">\r\n");
      out.write("                <img src=\"https://www.pngall.com/wp-content/uploads/13/Search-Button-Black-PNG-Cutout.png\" alt=\"\" class=\"h-[40px] p-3\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex items-center mr-4\">\r\n");
      out.write("        	<div class=\"\">\r\n");
      out.write("                <a href=\"./register.jsp\" class=\"flex h-9 w-24 justify-center rounded-3xl items-center my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" style=\"fill: rgba(0, 0, 0, 1);transform: ;msFilter:;\">\r\n");
      out.write("                        <path d=\"M12 2a5 5 0 1 0 5 5 5 5 0 0 0-5-5zm0 8a3 3 0 1 1 3-3 3 3 0 0 1-3 3zm9 11v-1a7 7 0 0 0-7-7h-4a7 7 0 0 0-7 7v1h2v-1a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v1z\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <p class=\"ml-2\">Register</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <a href=\"./login.jsp\" class=\"flex h-9 w-24 justify-center rounded-3xl items-center my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" style=\"fill: rgba(0, 0, 0, 1);transform: ;msFilter:;\">\r\n");
      out.write("                        <path d=\"M12 2a5 5 0 1 0 5 5 5 5 0 0 0-5-5zm0 8a3 3 0 1 1 3-3 3 3 0 0 1-3 3zm9 11v-1a7 7 0 0 0-7-7h-4a7 7 0 0 0-7 7v1h2v-1a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v1z\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <p class=\"ml-2\">Login</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <a href=\"\" class=\"flex h-9 w-24 justify-center rounded-3xl items-center my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" style=\"fill: rgba(0, 0, 0, 1);transform: ;msFilter:;\">\r\n");
      out.write("                        <path d=\"M21.822 7.431A1 1 0 0 0 21 7H7.333L6.179 4.23A1.994 1.994 0 0 0 4.333 3H2v2h2.333l4.744 11.385A1 1 0 0 0 10 17h8c.417 0 .79-.259.937-.648l3-8a1 1 0 0 0-.115-.921zM17.307 15h-6.64l-2.5-6h11.39l-2.25 6z\"></path>\r\n");
      out.write("                        <circle cx=\"10.5\" cy=\"19.5\" r=\"1.5\"></circle>\r\n");
      out.write("                        <circle cx=\"17.5\" cy=\"19.5\" r=\"1.5\"></circle>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <p class=\"ml-2\">Cart</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"bg-white shadow-md\">\r\n");
      out.write("        <div class=\"container mx-auto px-4 py-2\">\r\n");
      out.write("            <div class=\"flex justify-between items-center\">\r\n");
      out.write("                <!-- Logo -->\r\n");
      out.write("                <a href=\"#\" class=\"text-indigo-500 font-bold text-lg\">Kyube Gadget</a>\r\n");
      out.write("                <!-- Navigation Links -->\r\n");
      out.write("                <div class=\"hidden md:block\">\r\n");
      out.write("                    <a href=\"./index.jsp\" class=\"my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">Home</a>\r\n");
      out.write("                    <a href=\"#\" class=\"my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">About</a>\r\n");
      out.write("                    <a href=\"#\" class=\"my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">Contact Us</a>\r\n");
      out.write("                    <!-- Categories Dropdown -->\r\n");
      out.write("                    <div class=\"relative inline-block\">\r\n");
      out.write("                        <button class=\"dropdown-button my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500 focus:outline-none\">Categories</button>\r\n");
      out.write("                        <div class=\"dropdown-menu absolute hidden z-10 left-0  mt-2 w-40 bg-white shadow-md rounded-md \">\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Smartphones & Accessories</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Computers & Laptops</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Home Entertainment</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Photography & Cameras</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Wearable Technology</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Mobile Menu Button (Hidden on desktop) -->\r\n");
      out.write("                <div class=\"md:hidden\">\r\n");
      out.write("                    <button class=\"text-gray-800 focus:outline-none\">\r\n");
      out.write("                        <!-- Hamburger icon -->\r\n");
      out.write("                        <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    // Get the categories button and dropdown menu\r\n");
      out.write("    var categoriesButton = document.querySelector('.dropdown-button');\r\n");
      out.write("    var dropdownMenu = document.querySelector('.dropdown-menu');\r\n");
      out.write("\r\n");
      out.write("    // Add event listener to the categories button\r\n");
      out.write("    categoriesButton.addEventListener('click', function() {\r\n");
      out.write("        // Toggle the visibility of the dropdown menu\r\n");
      out.write("        dropdownMenu.classList.toggle('hidden');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Close dropdown menu when clicking outside of it\r\n");
      out.write("    document.addEventListener('click', function(event) {\r\n");
      out.write("        if (!categoriesButton.contains(event.target) && !dropdownMenu.contains(event.target)) {\r\n");
      out.write("            dropdownMenu.classList.add('hidden');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ✅ Grid Section - Starts Here 👇 -->\r\n");
      out.write("<section id=\"Projects\" class=\"mx-auto mb-5 mt-10 grid w-fit grid-cols-1 justify-center justify-items-center gap-x-14 gap-y-20 md:grid-cols-2 lg:grid-cols-3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--   ✅ Product card 1 - Starts Here 👇 -->\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"./insideProduct.jsp\">\r\n");
      out.write("      <img src=\"https://www.bhphotovideo.com/images/images2500x2500/apple_mgyj3am_a_airpods_max_silver_1610234.jpg\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">APPLE</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Airpods</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   🛑 Product card 1 - Ends Here  -->\r\n");
      out.write("\r\n");
      out.write("  <!--   ✅ Product card 2 - Starts Here 👇 -->\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"./insideProduct.jsp\">\r\n");
      out.write("      <img src=\"https://choicemandu.com/image/cache/catalog/iphone/iwatch-1000x1000.jpg\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Apple</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Watch Ultra</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$200</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$250</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   🛑 Product card 2- Ends Here  -->\r\n");
      out.write("\r\n");
      out.write("  <!--   ✅ Product card 3 - Starts Here 👇 -->\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://images.unsplash.com/photo-1651950537598-373e4358d320?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8MjV8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   🛑 Product card 3 - Ends Here  -->\r\n");
      out.write("\r\n");
      out.write("  <!--   ✅ Product card 4 - Starts Here 👇 -->\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://images.unsplash.com/photo-1651950540805-b7c71869e689?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8Mjl8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   🛑 Product card 4 - Ends Here  -->\r\n");
      out.write("\r\n");
      out.write("  <!--   ✅ Product card 5 - Starts Here 👇 -->\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://sony.scene7.com/is/image/sonyglobalsolutions/og-2?$categorypdpnav$&fmt=png-alpha\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   🛑 Product card 5 - Ends Here  -->\r\n");
      out.write("\r\n");
      out.write("  <!--   ✅ Product card 6 - Starts Here 👇 -->\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone15prohero-202309_FMT_WHH?wid=508&hei=472&fmt=p-jpg&qlt=95&.v=1693086369818\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   🛑 Product card 6 - Ends Here  -->\r\n");
      out.write("  \r\n");
      out.write("  <!-- product 7,8,9 start -->\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone15prohero-202309_FMT_WHH?wid=508&hei=472&fmt=p-jpg&qlt=95&.v=1693086369818\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone15prohero-202309_FMT_WHH?wid=508&hei=472&fmt=p-jpg&qlt=95&.v=1693086369818\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"w-72 rounded-xl bg-white shadow-md duration-500 hover:scale-105 hover:shadow-xl\">\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <img src=\"https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone15prohero-202309_FMT_WHH?wid=508&hei=472&fmt=p-jpg&qlt=95&.v=1693086369818\" alt=\"Product\" class=\"h-80 w-72 rounded-t-xl object-cover\" />\r\n");
      out.write("      <div class=\"w-72 px-4 py-3\">\r\n");
      out.write("        <span class=\"mr-3 text-xs uppercase text-gray-400\">Brand</span>\r\n");
      out.write("        <p class=\"block truncate text-lg font-bold capitalize text-black\">Product Name</p>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("          <p class=\"my-3 cursor-auto text-lg font-semibold text-black\">$149</p>\r\n");
      out.write("          <del>\r\n");
      out.write("            <p class=\"ml-2 cursor-auto text-sm text-gray-600\">$199</p>\r\n");
      out.write("          </del>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("          <button class=\"flex items-center text-sm text-white bg-gray-900 border-0 py-1 px-2 focus:outline-none hover:bg-gray-600 rounded\">Add to Cart\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Product 7,8,9 end -->\r\n");
      out.write("  \r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- 🛑 Grid Section - Ends Here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("<script src=\"https://storage.ko-fi.com/cdn/scripts/overlay-widget.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  kofiWidgetOverlay.draw('mohamedghulam', {\r\n");
      out.write("          'type': 'floating-chat',\r\n");
      out.write("          'floating-chat.donateButton.text': 'Contact Us',\r\n");
      out.write("          'floating-chat.donateButton.background-color': '#323842',\r\n");
      out.write("          'floating-chat.donateButton.text-color': '#fff'\r\n");
      out.write("      });\r\n");
      out.write("</script>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/output.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"px-4 pt-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 \">\r\n");
      out.write("  <div class=\"grid gap-10 row-gap-6 mb-8 sm:grid-cols-2 lg:grid-cols-4\">\r\n");
      out.write("    <div class=\"sm:col-span-2\">\r\n");
      out.write("      <a href=\"/\" aria-label=\"Go home\" title=\"Company\" class=\"inline-flex items-center\">\r\n");
      out.write("        <svg class=\"w-8 text-deep-purple-accent-400\" viewBox=\"0 0 24 24\" stroke-linejoin=\"round\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-miterlimit=\"10\" stroke=\"currentColor\" fill=\"none\">\r\n");
      out.write("          <rect x=\"3\" y=\"1\" width=\"7\" height=\"12\"></rect>\r\n");
      out.write("          <rect x=\"3\" y=\"17\" width=\"7\" height=\"6\"></rect>\r\n");
      out.write("          <rect x=\"14\" y=\"1\" width=\"7\" height=\"6\"></rect>\r\n");
      out.write("          <rect x=\"14\" y=\"11\" width=\"7\" height=\"12\"></rect>\r\n");
      out.write("        </svg>\r\n");
      out.write("        <span class=\"ml-2 text-xl font-bold tracking-wide text-indigo-500 uppercase\">Kyube Gadget</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"mt-6 lg:max-w-sm\">\r\n");
      out.write("        <p class=\"text-sm text-gray-800\">\r\n");
      out.write("          Kyube Gadget: Your one-stop shop for cutting-edge electronics. Explore our range of top-quality gadgets and devices. Shop now for the latest in tech innovation!\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"space-y-2 text-sm\">\r\n");
      out.write("      <p class=\"text-base font-bold tracking-wide text-indigo-500\">Contacts</p>\r\n");
      out.write("      <div class=\"flex\">\r\n");
      out.write("        <p class=\"mr-1 text-gray-800\">Phone:</p>\r\n");
      out.write("        <a href=\"#\" aria-label=\"Our phone\" title=\"Our phone\" class=\"transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800\">+9779876543210</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"flex\">\r\n");
      out.write("        <p class=\"mr-1 text-gray-800\">Email:</p>\r\n");
      out.write("        <a href=\"mailto:info@lorem.mail\" aria-label=\"Our email\" title=\"Our email\" class=\"transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800\">kyubegadget@gmail.com</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"flex\">\r\n");
      out.write("        <p class=\"mr-1 text-gray-800\">Address:</p>\r\n");
      out.write("        <a href=\"https://www.google.com/maps\" target=\"_blank\" rel=\"noopener noreferrer\" aria-label=\"Our address\" title=\"Our address\" class=\"transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800\">\r\n");
      out.write("          Sarweshwor Marg, Pokhara 4 33700\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <span class=\"text-base font-bold tracking-wide text-indigo-500\">Social</span>\r\n");
      out.write("      <div class=\"flex items-center mt-1 space-x-3\">\r\n");
      out.write("        <a href=\"/\" class=\"text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400\">\r\n");
      out.write("          <svg viewBox=\"0 0 24 24\" fill=\"currentColor\" class=\"h-5\">\r\n");
      out.write("            <path\r\n");
      out.write("              d=\"M24,4.6c-0.9,0.4-1.8,0.7-2.8,0.8c1-0.6,1.8-1.6,2.2-2.7c-1,0.6-2,1-3.1,1.2c-0.9-1-2.2-1.6-3.6-1.6 c-2.7,0-4.9,2.2-4.9,4.9c0,0.4,0,0.8,0.1,1.1C7.7,8.1,4.1,6.1,1.7,3.1C1.2,3.9,1,4.7,1,5.6c0,1.7,0.9,3.2,2.2,4.1 C2.4,9.7,1.6,9.5,1,9.1c0,0,0,0,0,0.1c0,2.4,1.7,4.4,3.9,4.8c-0.4,0.1-0.8,0.2-1.3,0.2c-0.3,0-0.6,0-0.9-0.1c0.6,2,2.4,3.4,4.6,3.4 c-1.7,1.3-3.8,2.1-6.1,2.1c-0.4,0-0.8,0-1.2-0.1c2.2,1.4,4.8,2.2,7.5,2.2c9.1,0,14-7.5,14-14c0-0.2,0-0.4,0-0.6 C22.5,6.4,23.3,5.5,24,4.6z\"\r\n");
      out.write("            ></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"/\" class=\"text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400\">\r\n");
      out.write("          <svg viewBox=\"0 0 30 30\" fill=\"currentColor\" class=\"h-6\">\r\n");
      out.write("            <circle cx=\"15\" cy=\"15\" r=\"4\"></circle>\r\n");
      out.write("            <path\r\n");
      out.write("              d=\"M19.999,3h-10C6.14,3,3,6.141,3,10.001v10C3,23.86,6.141,27,10.001,27h10C23.86,27,27,23.859,27,19.999v-10   C27,6.14,23.859,3,19.999,3z M15,21c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S18.309,21,15,21z M22,9c-0.552,0-1-0.448-1-1   c0-0.552,0.448-1,1-1s1,0.448,1,1C23,8.552,22.552,9,22,9z\"\r\n");
      out.write("            ></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"/\" class=\"text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400\">\r\n");
      out.write("          <svg viewBox=\"0 0 24 24\" fill=\"currentColor\" class=\"h-5\">\r\n");
      out.write("            <path\r\n");
      out.write("              d=\"M22,0H2C0.895,0,0,0.895,0,2v20c0,1.105,0.895,2,2,2h11v-9h-3v-4h3V8.413c0-3.1,1.893-4.788,4.659-4.788 c1.325,0,2.463,0.099,2.795,0.143v3.24l-1.918,0.001c-1.504,0-1.795,0.715-1.795,1.763V11h4.44l-1,4h-3.44v9H22c1.105,0,2-0.895,2-2 V2C24,0.895,23.105,0,22,0z\"\r\n");
      out.write("            ></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <p class=\"mt-4 text-sm text-gray-500\">\r\n");
      out.write("        Follow us on different social media to keep up with our daily updates\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"flex flex-col-reverse justify-between pt-5 pb-10 border-t lg:flex-row\">\r\n");
      out.write("    <p class=\"text-sm text-indigo-500\">\r\n");
      out.write("      © Copyright 2024 Kyube Gadget. All rights reserved.\r\n");
      out.write("    </p>\r\n");
      out.write("    <ul class=\"flex flex-col mb-3 space-y-2 lg:mb-0 sm:space-y-0 sm:space-x-5 sm:flex-row\">\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"/\" class=\"text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400\">F.A.Q</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"/\" class=\"text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400\">Privacy Policy</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"/\" class=\"text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400\">Terms &amp; Conditions</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
