/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-01 13:41:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/output.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"max-h-[70px]\">\r\n");
      out.write("    <div class=\"flex justify-between mt-2\">\r\n");
      out.write("        <div class=\"ml-5 flex items-center\">\r\n");
      out.write("            <svg class=\"w-8 text-deep-purple-accent-400\" viewBox=\"0 0 24 24\" stroke-linejoin=\"round\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-miterlimit=\"10\" stroke=\"currentColor\" fill=\"none\">\r\n");
      out.write("                <rect x=\"3\" y=\"1\" width=\"7\" height=\"12\"></rect>\r\n");
      out.write("                <rect x=\"3\" y=\"17\" width=\"7\" height=\"6\"></rect>\r\n");
      out.write("                <rect x=\"14\" y=\"1\" width=\"7\" height=\"6\"></rect>\r\n");
      out.write("                <rect x=\"14\" y=\"11\" width=\"7\" height=\"12\"></rect>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("            <input type=\"text\" class=\"h-[40px] border border-b-gray-200 pl-4 rounded-s-full\" placeholder=\"Search\">\r\n");
      out.write("            <div class=\"h-[40px] border border-b-gray-200 rounded-e-full hover:bg-slate-200 hover:border-indigo-700 \">\r\n");
      out.write("                <img src=\"https://www.pngall.com/wp-content/uploads/13/Search-Button-Black-PNG-Cutout.png\" alt=\"\" class=\"h-[40px] p-3\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex items-center mr-4\">\r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <a href=\"\" class=\"flex h-9 w-24 justify-center rounded-3xl items-center my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" style=\"fill: rgba(0, 0, 0, 1);transform: ;msFilter:;\">\r\n");
      out.write("                        <path d=\"M12 2a5 5 0 1 0 5 5 5 5 0 0 0-5-5zm0 8a3 3 0 1 1 3-3 3 3 0 0 1-3 3zm9 11v-1a7 7 0 0 0-7-7h-4a7 7 0 0 0-7 7v1h2v-1a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v1z\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <p class=\"ml-2\">Sign in</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <a href=\"\" class=\"flex h-9 w-24 justify-center rounded-3xl items-center my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" style=\"fill: rgba(0, 0, 0, 1);transform: ;msFilter:;\">\r\n");
      out.write("                        <path d=\"M21.822 7.431A1 1 0 0 0 21 7H7.333L6.179 4.23A1.994 1.994 0 0 0 4.333 3H2v2h2.333l4.744 11.385A1 1 0 0 0 10 17h8c.417 0 .79-.259.937-.648l3-8a1 1 0 0 0-.115-.921zM17.307 15h-6.64l-2.5-6h11.39l-2.25 6z\"></path>\r\n");
      out.write("                        <circle cx=\"10.5\" cy=\"19.5\" r=\"1.5\"></circle>\r\n");
      out.write("                        <circle cx=\"17.5\" cy=\"19.5\" r=\"1.5\"></circle>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <p class=\"ml-2\">Cart</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"bg-white shadow-md\">\r\n");
      out.write("        <div class=\"container mx-auto px-4 py-2\">\r\n");
      out.write("            <div class=\"flex justify-between items-center\">\r\n");
      out.write("                <!-- Logo -->\r\n");
      out.write("                <a href=\"#\" class=\"text-indigo-500 font-bold text-lg\">Kyube Gadgets</a>\r\n");
      out.write("                <!-- Navigation Links -->\r\n");
      out.write("                <div class=\"hidden md:block\">\r\n");
      out.write("                    <a href=\"#\" class=\"my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">Home</a>\r\n");
      out.write("                    <a href=\"#\" class=\"my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">About</a>\r\n");
      out.write("                    <a href=\"#\" class=\"my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500\">Contact Us</a>\r\n");
      out.write("                    <!-- Categories Dropdown -->\r\n");
      out.write("                    <div class=\"relative inline-block\">\r\n");
      out.write("                        <button class=\"dropdown-button my-1 mx-4 text-sm text-gray-700 font-medium hover:text-indigo-500 focus:outline-none\">Categories</button>\r\n");
      out.write("                        <div class=\"dropdown-menu absolute hidden z-10 left-0  mt-2 w-40 bg-white shadow-md rounded-md \">\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Smartphones & Accessories</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Computers & Laptops</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Home Entertainment</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Photography & Cameras</a>\r\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">Wearable Technology</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Mobile Menu Button (Hidden on desktop) -->\r\n");
      out.write("                <div class=\"md:hidden\">\r\n");
      out.write("                    <button class=\"text-gray-800 focus:outline-none\">\r\n");
      out.write("                        <!-- Hamburger icon -->\r\n");
      out.write("                        <svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    // Get the categories button and dropdown menu\r\n");
      out.write("    var categoriesButton = document.querySelector('.dropdown-button');\r\n");
      out.write("    var dropdownMenu = document.querySelector('.dropdown-menu');\r\n");
      out.write("\r\n");
      out.write("    // Add event listener to the categories button\r\n");
      out.write("    categoriesButton.addEventListener('click', function() {\r\n");
      out.write("        // Toggle the visibility of the dropdown menu\r\n");
      out.write("        dropdownMenu.classList.toggle('hidden');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Close dropdown menu when clicking outside of it\r\n");
      out.write("    document.addEventListener('click', function(event) {\r\n");
      out.write("        if (!categoriesButton.contains(event.target) && !dropdownMenu.contains(event.target)) {\r\n");
      out.write("            dropdownMenu.classList.add('hidden');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
